---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaRole:
    Type: String
    MinLength : '1'
    Description: lambda IAM role with neccessary permissions
  BucketName:
    Type: String
    MinLength : '1'
    Description: S3 bucket name in which lambda fuction resides
  LambdaFolderPath:
    Type: String
    MinLength : '1'
    Description: Folder path in which lambda fuction resides
Resources:
  Myfunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Myfunction
      Handler: index.handler
      Role: 
        Fn::Sub:
        - arn:aws:iam::431508442254:role/${Role}
        - Role:
           Ref: LambdaRole
      Code:
        #S3Bucket: lambdafunction2027
        S3Bucket: 
          Ref: BucketName
        #S3Key: code/mylambda.zip
        S3Key: 
          Fn::Sub:
          - ${LambdaPath}/mylambda.zip
          - LambdaPath:
              Ref: LambdaFolderPath
      Runtime: nodejs14.x
